version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: productlayback1
      POSTGRES_DB: productlayback1
    ports:
      - '8082:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
